# Railway Backend Configuration
# Railway will automatically detect this as a Node.js project

[deploy]
  startCommand = "npm run start:prod:be"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
